### ISSUE TITLE
Can you share the code of 'The effect of climate change on the resilience of ecosystems with adaptive spatial pattern formation'

### ISSUE THREAD

**Issue by chenzheng1996** [Bastiaansen/Bastiaansen.github.io#1]
I am reading your article and interested in ‘’The effect of climate change on the resilience of ecosystems with adaptive spatial pattern formation‘’ can you share the code of it especially the bifurcation diagram. i would appreciated if you can reply.

**Comment by Bastiaansen** [comment]
Hi!

Sure I can share the code with you. But please note that the only numerical simulation in that article are reported on in Figures 4-7; the others are illustrations to communicate the system's structure. So I only have a code for the simulations with the migration-ODE and stability criterium for the extended-Klausmeier model (as developed in the more technical paper https://doi.org/10.1016/j.physd.2018.09.003).

But please do **send me an email** (r.bastiaansen@uu.nl) and I will send the code to you, and can help you further if you'd like.

-Robbin
